apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node
spec:
  selector:
    matchLabels:
      app: my-node
  template:
    metadata:
      labels:
        app: my-node
    spec:
      containers:
      - name: my-node
        image: lazizbekkahramonov/my-node:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-service
spec:
  selector:
    app: my-node
  ports:
  - port: 3000
    targetPort: 3000

